[build]
  command = "npm run build"
  publish = "dist/portfolio"

# Override default plugins (disable automatic angular-runtime)
[[plugins]]
  package = "@netlify/plugin-sitemap" # or any dummy plugin to override
